In [84]:
import pandas as pd

In [85]:
df = pd.read_csv("/content/Medical Appointment No Shows.csv")
df.head(10)

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
5,9.598513e+13,5626772,F,2016-04-27T08:36:51Z,2016-04-29T00:00:00Z,76,REPÚBLICA,0,1,0,0,0,0,No
6,7.336882e+14,5630279,F,2016-04-27T15:05:12Z,2016-04-29T00:00:00Z,23,GOIABEIRAS,0,0,0,0,0,0,Yes
7,3.449833e+12,5630575,F,2016-04-27T15:39:58Z,2016-04-29T00:00:00Z,39,GOIABEIRAS,0,0,0,0,0,0,Yes
8,5.639473e+13,5638447,F,2016-04-29T08:02:16Z,2016-04-29T00:00:00Z,21,ANDORINHAS,0,0,0,0,0,0,No
9,7.812456e+13,5629123,F,2016-04-27T12:48:25Z,2016-04-29T00:00:00Z,19,CONQUISTA,0,0,0,0,0,0,No

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  object
 4   AppointmentDay  110527 non-null  object
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB

In [87]:
df.isnull().sum()

PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

In [88]:
df.columns

Index(['PatientId', 'AppointmentID', 'Gender', 'ScheduledDay',
       'AppointmentDay', 'Age', 'Neighbourhood', 'Scholarship', 'Hipertension',
       'Diabetes', 'Alcoholism', 'Handcap', 'SMS_received', 'No-show'],
      dtype='object')

In [89]:
for col in df.columns:
  print(col,'\n',df[col].unique(),'\n')

PatientId
 [2.98724998e+13 5.58997777e+14 4.26296230e+12 ... 7.26331493e+13
 9.96997666e+14 1.55766317e+13]

AppointmentID
 [5642903 5642503 5642549 ... 5630692 5630323 5629448]

Gender
 ['F' 'M']

ScheduledDay
 ['2016-04-29T18:38:08Z' '2016-04-29T16:08:27Z' '2016-04-29T16:19:04Z' ...
 '2016-04-27T16:03:52Z' '2016-04-27T15:09:23Z' '2016-04-27T13:30:56Z']

AppointmentDay
 ['2016-04-29T00:00:00Z' '2016-05-03T00:00:00Z' '2016-05-10T00:00:00Z'
 '2016-05-17T00:00:00Z' '2016-05-24T00:00:00Z' '2016-05-31T00:00:00Z'
 '2016-05-02T00:00:00Z' '2016-05-30T00:00:00Z' '2016-05-16T00:00:00Z'
 '2016-05-04T00:00:00Z' '2016-05-19T00:00:00Z' '2016-05-12T00:00:00Z'
 '2016-05-06T00:00:00Z' '2016-05-20T00:00:00Z' '2016-05-05T00:00:00Z'
 '2016-05-13T00:00:00Z' '2016-05-09T00:00:00Z' '2016-05-25T00:00:00Z'
 '2016-05-11T00:00:00Z' '2016-05-18T00:00:00Z' '2016-05-14T00:00:00Z'
 '2016-06-02T00:00:00Z' '2016-06-03T00:00:00Z' '2016-06-06T00:00:00Z'
 '2016-06-07T00:00:00Z' '2016-06-01T00:00:00Z' '2016-06-08T00:00:00Z']

Age
 [ 62  56   8  76  23  39  21  19  30  29  22  28  54  15  50  40  46   4
  13  65  45  51  32  12  61  38  79  18  63  64  85  59  55  71  49  78
  31  58  27   6   2  11   7   0   3   1  69  68  60  67  36  10  35  20
  26  34  33  16  42   5  47  17  41  44  37  24  66  77  81  70  53  75
  73  52  74  43  89  57  14   9  48  83  72  25  80  87  88  84  82  90
  94  86  91  98  92  96  93  95  97 102 115 100  99  -1]

Neighbourhood
 ['JARDIM DA PENHA' 'MATA DA PRAIA' 'PONTAL DE CAMBURI' 'REPÚBLICA'
 'GOIABEIRAS' 'ANDORINHAS' 'CONQUISTA' 'NOVA PALESTINA' 'DA PENHA'
 'TABUAZEIRO' 'BENTO FERREIRA' 'SÃO PEDRO' 'SANTA MARTHA' 'SÃO CRISTÓVÃO'
 'MARUÍPE' 'GRANDE VITÓRIA' 'SÃO BENEDITO' 'ILHA DAS CAIEIRAS'
 'SANTO ANDRÉ' 'SOLON BORGES' 'BONFIM' 'JARDIM CAMBURI' 'MARIA ORTIZ'
 'JABOUR' 'ANTÔNIO HONÓRIO' 'RESISTÊNCIA' 'ILHA DE SANTA MARIA'
 'JUCUTUQUARA' 'MONTE BELO' 'MÁRIO CYPRESTE' 'SANTO ANTÔNIO' 'BELA VISTA'
 'PRAIA DO SUÁ' 'SANTA HELENA' 'ITARARÉ' 'INHANGUETÁ' 'UNIVERSITÁRIO'
 'SÃO JOSÉ' 'REDENÇÃO' 'SANTA CLARA' 'CENTRO' 'PARQUE MOSCOSO'
 'DO MOSCOSO' 'SANTOS DUMONT' 'CARATOÍRA' 'ARIOVALDO FAVALESSA'
 'ILHA DO FRADE' 'GURIGICA' 'JOANA D´ARC' 'CONSOLAÇÃO' 'PRAIA DO CANTO'
 'BOA VISTA' 'MORADA DE CAMBURI' 'SANTA LUÍZA' 'SANTA LÚCIA'
 'BARRO VERMELHO' 'ESTRELINHA' 'FORTE SÃO JOÃO' 'FONTE GRANDE'
 'ENSEADA DO SUÁ' 'SANTOS REIS' 'PIEDADE' 'JESUS DE NAZARETH'
 'SANTA TEREZA' 'CRUZAMENTO' 'ILHA DO PRÍNCIPE' 'ROMÃO' 'COMDUSA'
 'SANTA CECÍLIA' 'VILA RUBIM' 'DE LOURDES' 'DO QUADRO' 'DO CABRAL' 'HORTO'
 'SEGURANÇA DO LAR' 'ILHA DO BOI' 'FRADINHOS' 'NAZARETH' 'AEROPORTO'
 'ILHAS OCEÂNICAS DE TRINDADE' 'PARQUE INDUSTRIAL']

Scholarship
 [0 1]

Hipertension
 [1 0]

Diabetes
 [0 1]

Alcoholism
 [0 1]

Handcap
 [0 1 2 3 4]

SMS_received
 [0 1]

No-show
 ['No' 'Yes']

In [90]:
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [91]:
def modify_col(df):
    # Convert to clean format
    df.columns = [col.strip().lower().replace("-", "_") for col in df.columns]
    # Fix spelling mistakes
    df.rename(columns={"handcap": "handicap", "hipertension": "hypertension", "patientid": "patient_id", "appointmentid": "appointment_id",
                       "scheduledday" : "scheduled_day", "appointmentday": "appointment_day"}, inplace=True)
    return df

In [92]:
df = modify_col(df)

In [93]:
df['gender'] = df['gender'].str.lower().str.strip()
df['no_show'] = df['no_show'].str.lower().str.strip()
df['neighbourhood'] = df['neighbourhood'].str.title().str.strip()

In [94]:
df

,patient_id,appointment_id,gender,scheduled_day,appointment_day,age,neighbourhood,scholarship,hypertension,diabetes,alcoholism,handicap,sms_received,no_show
0,2.987250e+13,5642903,f,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,Jardim Da Penha,0,1,0,0,0,0,no
1,5.589978e+14,5642503,m,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,Jardim Da Penha,0,0,0,0,0,0,no
2,4.262962e+12,5642549,f,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,Mata Da Praia,0,0,0,0,0,0,no
3,8.679512e+11,5642828,f,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,Pontal De Camburi,0,0,0,0,0,0,no
4,8.841186e+12,5642494,f,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,Jardim Da Penha,0,1,1,0,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,f,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,Maria Ortiz,0,0,0,0,0,1,no
110523,3.596266e+12,5650093,f,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,Maria Ortiz,0,0,0,0,0,1,no
110524,1.557663e+13,5630692,f,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,Maria Ortiz,0,0,0,0,0,1,no
110525,9.213493e+13,5630323,f,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,Maria Ortiz,0,0,0,0,0,1,no
110526,3.775115e+14,5629448,f,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,Maria Ortiz,0,0,0,0,0,1,no

In [95]:
df["gender"]= df["gender"].replace({"f": "female", "m": "male"})
df

,patient_id,appointment_id,gender,scheduled_day,appointment_day,age,neighbourhood,scholarship,hypertension,diabetes,alcoholism,handicap,sms_received,no_show
0,2.987250e+13,5642903,female,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,Jardim Da Penha,0,1,0,0,0,0,no
1,5.589978e+14,5642503,male,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,Jardim Da Penha,0,0,0,0,0,0,no
2,4.262962e+12,5642549,female,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,Mata Da Praia,0,0,0,0,0,0,no
3,8.679512e+11,5642828,female,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,Pontal De Camburi,0,0,0,0,0,0,no
4,8.841186e+12,5642494,female,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,Jardim Da Penha,0,1,1,0,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,female,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,Maria Ortiz,0,0,0,0,0,1,no
110523,3.596266e+12,5650093,female,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,Maria Ortiz,0,0,0,0,0,1,no
110524,1.557663e+13,5630692,female,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,Maria Ortiz,0,0,0,0,0,1,no
110525,9.213493e+13,5630323,female,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,Maria Ortiz,0,0,0,0,0,1,no
110526,3.775115e+14,5629448,female,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,Maria Ortiz,0,0,0,0,0,1,no

In [96]:
df['scheduled_day'] = pd.to_datetime(df['scheduled_day'])
df['appointment_day'] = pd.to_datetime(df['appointment_day'])
df['patient_id'] = df['patient_id'].astype(str)

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   patient_id       110527 non-null  object
 1   appointment_id   110527 non-null  int64
 2   gender           110527 non-null  object
 3   scheduled_day    110527 non-null  datetime64[ns, UTC]
 4   appointment_day  110527 non-null  datetime64[ns, UTC]
 5   age              110527 non-null  int64
 6   neighbourhood    110527 non-null  object
 7   scholarship      110527 non-null  int64
 8   hypertension     110527 non-null  int64
 9   diabetes         110527 non-null  int64
 10  alcoholism       110527 non-null  int64
 11  handicap         110527 non-null  int64
 12  sms_received     110527 non-null  int64
 13  no_show          110527 non-null  object
dtypes: datetime64[ns, UTC](2), int64(8), object(4)
memory usage: 11.8+ MB

In [100]:
df['scheduled_day'] = df['scheduled_day'].dt.tz_localize(None)
df['appointment_day'] = df['appointment_day'].dt.tz_localize(None)

In [102]:
df.dtypes

patient_id                 object
appointment_id              int64
gender                     object
scheduled_day      datetime64[ns]
appointment_day    datetime64[ns]
age                         int64
neighbourhood              object
scholarship                 int64
hypertension                int64
diabetes                    int64
alcoholism                  int64
handicap                    int64
sms_received                int64
no_show                    object
dtype: object

In [103]:
df

,patient_id,appointment_id,gender,scheduled_day,appointment_day,age,neighbourhood,scholarship,hypertension,diabetes,alcoholism,handicap,sms_received,no_show
0,29872499824296.0,5642903,female,2016-04-29 18:38:08,2016-04-29,62,Jardim Da Penha,0,1,0,0,0,0,no
1,558997776694438.0,5642503,male,2016-04-29 16:08:27,2016-04-29,56,Jardim Da Penha,0,0,0,0,0,0,no
2,4262962299951.0,5642549,female,2016-04-29 16:19:04,2016-04-29,62,Mata Da Praia,0,0,0,0,0,0,no
3,867951213174.0,5642828,female,2016-04-29 17:29:31,2016-04-29,8,Pontal De Camburi,0,0,0,0,0,0,no
4,8841186448183.0,5642494,female,2016-04-29 16:07:23,2016-04-29,56,Jardim Da Penha,0,1,1,0,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2572134369293.0,5651768,female,2016-05-03 09:15:35,2016-06-07,56,Maria Ortiz,0,0,0,0,0,1,no
110523,3596266328735.0,5650093,female,2016-05-03 07:27:33,2016-06-07,51,Maria Ortiz,0,0,0,0,0,1,no
110524,15576631729893.0,5630692,female,2016-04-27 16:03:52,2016-06-07,21,Maria Ortiz,0,0,0,0,0,1,no
110525,92134931435557.0,5630323,female,2016-04-27 15:09:23,2016-06-07,38,Maria Ortiz,0,0,0,0,0,1,no
110526,377511518121127.0,5629448,female,2016-04-27 13:30:56,2016-06-07,54,Maria Ortiz,0,0,0,0,0,1,no

In [104]:
df.to_csv("cleaned_medical_appointments.csv", index=False)

In [105]:
from google.colab import files
files.download("cleaned_medical_appointments.csv")